// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DialogServer 负责为业务层添加中间件逻辑和兜底等措施
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {number} screenX
 * @param {number} screenY
 * @returns {$CancellablePromise<string>}
 */
export function SayHello(screenX, screenY) {
    return $Call.ByID(3951517854, screenX, screenY);
}
